---
- name: Create "exadmn" User, add the public-key, and add it to Sudoers
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_user: "{{ survey_ansible_user }}"
    ansible_port: "{{ survey_ansible_port }}"
  tasks:
    - name: Identify Linux distribution
      set_fact:
        linux_distribution: "{{ ansible_facts['distribution'] | lower }}"

    - name: Create 'exadmn' User
      user:
        name: "exadmn"
        comment: "Ansible-Tower-AdminUser"
        home: "/home/exadmn"
        shell: /bin/bash

    - name: Create 'exadmn' home directory
      file:
        path: "/home/exadmn"
        state: directory
        mode: "0755"
        owner: exadmn
        group: exadmn

    - name: Create .ssh folder
      file:
        path: /home/exadmn/.ssh
        state: directory
        mode: "0700"
        owner: exadmn
        group: exadmn

    - name: Add Public-Key to authorized_keys
      authorized_key:
        user: "exadmn"
        key: "{{ lookup('file', './other/public_key.pub') }}"
        state: present

    - name: Add 'exadmn' User to Sudoers file for Rhel based distro
      lineinfile:
        path: /etc/sudoers
        insertafter: "^## Allow root to run any commands anywhere"
        line: "exadmn ALL=(ALL:ALL) NOPASSWD: ALL"
        create: yes
        validate: "visudo -cf %s"
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Add 'exadmn' User to Sudoers file for Debain based distro
      lineinfile:
        path: /etc/sudoers
        insertafter: "^# Allow members of group sudo to execute any command"
        line: "exadmn ALL=(ALL:ALL) NOPASSWD: ALL"
        create: yes
        validate: "visudo -cf %s"
      when: linux_distribution == 'ubuntu'

    - name: Update the 'MOTD' file
      copy:
        content: |
            _______  __ ___    __  ______  ___________               
          / ____/ |/ //   |  / / / / __ \/ ___/_  __/               
          / __/  |   // /| | / /_/ / / / /\__ \ / /                  
        / /___ /   |/ ___ |/ __  / /_/ /___/ // /                   
        /_____//_/|_/_/  |_/_/ /_/\____//____//_/                    
                          __  ______    _   _____   ________________ 
                        /  |/  /   |  / | / /   | / ____/ ____/ __ \
                        / /|_/ / /| | /  |/ / /| |/ / __/ __/ / / / /
                      / /  / / ___ |/ /|  / ___ / /_/ / /___/ /_/ / 
                      /_/  /_/_/  |_/_/ |_/_/  |_\____/_____/_____/  
        dest: /etc/motd
