---
- name: Create "exadmn" user, add the public key, and add it to sudoers
  hosts: all
  become: yes
  gather_facts: true
  vars:
    ansible_port: "{{ survey_ansible_port }}"
  tasks:
    - name: Identify Linux distribution
      set_fact:
        linux_distribution: "{{ ansible_facts['distribution'] | lower }}"

    - name: Create exadmn user
      user:
        name: "exadmn"
        comment: "Ansible-Tower-AdminUser"
        home: "/home/exadmn"
        shell: /bin/bash

    - name: Create exadmn home directory
      file:
        path: "/home/exadmn"
        state: directory
        mode: "0755"
        owner: exadmn
        group: exadmn

    - name: Create .ssh folder
      file:
        path: /home/exadmn/.ssh
        state: directory
        mode: "0700"
        owner: exadmn
        group: exadmn

    - name: Add public key to authorized_keys
      authorized_key:
        user: "exadmn"
        key: "{{ lookup('file', './other/public_key.pub') }}"
        state: present

    - name: Add exadmn user to sudoers file for rhel based distro
      lineinfile:
        path: /etc/sudoers
        insertafter: "^## Allow root to run any commands anywhere"
        line: "exadmn ALL=(ALL) NOPASSWD: ALL"
        create: yes
        validate: "visudo -cf %s"
      become_user: root
      become_method: sudo
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Add exadmn user to sudoers file for debain based distro
      lineinfile:
        path: /etc/sudoers
        insertafter: "^# User privilege specification"
        line: "exadmn ALL=(ALL) NOPASSWD: ALL"
        create: yes
        validate: "visudo -cf %s"
      become_user: root
      become_method: sudo
      when: linux_distribution == 'ubuntu'
